### ISSUE TITLE
org.spongepowered.gradle.vanilla.internal.ProvideMinecraftPlugin

### ISSUE THREAD

**Issue by ebullienc3** [SpongePowered/VanillaGradle#112] opened 2023-07-19 08:07 UTC
I have this problem when I try to build Croptopia ( https://github.com/ExcessiveAmountsOfZombies/jEEPersShops )
The same error as showed here: https://gist.github.com/ExcessiveAmountsOfZombies/94634aa015b6a1755206c28b6f469192

**Comment by zml2008** [comment] 2023-07-19 13:10
Duplicate of #111

**Closed by zml2008** 2023-07-19 13:10 UTC

**Comment by rockfordroeNG** [comment] 2023-07-28 23:58
I'm still having this issue after upgrading to Gradle 8.2.1 for FerriteCore

https://pastebin.com/XcZjaJkz
